### ISSUE TITLE
Link to the online version of my Personal-Portfolio

### ISSUE THREAD

**Issue by tashisrael** [tashisrael/Personal-Portfolio#8]
Hello there! 
Please click here [My Personal-Portfolio](https://tashisrael.github.io/Personal-Portfolio/) to view the online version of my portfolio page.

Cheers!

**Comment by zainsadaqat** [comment]
# Required Changes 🔁
# Hello @tashisrael and @Baayeh  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] Navigation link such as Portfolio and About isn't working. I'm unable to move to that section. Kindly fix this. 👍 

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tashisrael** [comment]
Thank you for that review. I have worked on it

**Comment by aimemalaika** [comment]
Hi @tashisrael , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
